-- ================================================================
-- MJM Audit — connect the audit system to Supabase properly
-- Run once in the Supabase SQL Editor (project kibqjztozokohqmhqqqf).
-- Safe to re-run. It adds and grants; it never drops a column or a row.
--
-- WHY THE APP SHOWS NOTHING
--
-- migration_rls_hardening.sql replaced the audit policies with
-- audit_module_read / audit_module_write, both TO authenticated and both
-- calling _mjm_has_module(audit, …). Two things then have to be true
-- before a single row comes back:
--
--   1. the request must arrive as an authenticated user, and
--   2. that user must have permissions.modules.audit set to admin/normal.
--
-- The app now satisfies (1) — audit_supabase.js sends the logins access
-- token. But (2) was never set up: auditors sign up through the audit
-- login, which creates a shared_profiles row with no permissions at all.
-- So every read is still filtered to zero rows, silently, because RLS
-- filters rather than errors.
--
-- This script replaces that check with one the audit team actually
-- passes — any signed-in MJM account that is not a customer — and splits
-- DELETE out so only admins get it. It also makes sure each table really
-- has the columns the app reads and writes, since the live tables were
-- created by hand rather than by the migration.
-- ================================================================

BEGIN;

-- ────────────────────────────────────────────────────────────────
-- 1. TABLES AND COLUMNS
--    CREATE IF NOT EXISTS leaves your existing tables and data alone;
--    the ADD COLUMN IF NOT EXISTS lines below fill in anything missing.
-- ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.audit_plot_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.audit_height_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.audit_papan_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.audit_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.audit_maintenance_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.audit_maintenance_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Every table is read with `order=created_at.desc`. A table without that
-- column fails the whole read with a 400 and the list looks empty.
ALTER TABLE public.audit_plot_audits        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.audit_height_records     ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.audit_papan_audits       ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.audit_batches            ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.audit_maintenance_tasks  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE public.audit_maintenance_audits ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

-- Plot Condition Audit — audit_script.js saveRecord()
ALTER TABLE public.audit_plot_audits
  ADD COLUMN IF NOT EXISTS audit_id     TEXT,
  ADD COLUMN IF NOT EXISTS nursery      TEXT,
  ADD COLUMN IF NOT EXISTS plot         TEXT,
  ADD COLUMN IF NOT EXISTS batch        TEXT,
  ADD COLUMN IF NOT EXISTS pest         TEXT,
  ADD COLUMN IF NOT EXISTS tikus        TEXT,
  ADD COLUMN IF NOT EXISTS disease      TEXT,
  ADD COLUMN IF NOT EXISTS warna_daun   TEXT,
  ADD COLUMN IF NOT EXISTS photo_url    TEXT,
  ADD COLUMN IF NOT EXISTS photo_2_url  TEXT,
  ADD COLUMN IF NOT EXISTS date         DATE,
  ADD COLUMN IF NOT EXISTS auditor_name TEXT;

-- Seedling Height Audit — audit_height_script.js saveRecord()
ALTER TABLE public.audit_height_records
  ADD COLUMN IF NOT EXISTS record_id    TEXT,
  ADD COLUMN IF NOT EXISTS nursery      TEXT,
  ADD COLUMN IF NOT EXISTS plot         TEXT,
  ADD COLUMN IF NOT EXISTS batch        TEXT,
  ADD COLUMN IF NOT EXISTS sample_1     NUMERIC,
  ADD COLUMN IF NOT EXISTS sample_2     NUMERIC,
  ADD COLUMN IF NOT EXISTS sample_3     NUMERIC,
  ADD COLUMN IF NOT EXISTS avg_height   NUMERIC,
  ADD COLUMN IF NOT EXISTS photo_1_url  TEXT,
  ADD COLUMN IF NOT EXISTS photo_2_url  TEXT,
  ADD COLUMN IF NOT EXISTS photo_3_url  TEXT,
  ADD COLUMN IF NOT EXISTS date         DATE,
  ADD COLUMN IF NOT EXISTS auditor_name TEXT;

-- Papan Tanda Audit — audit_papan_script.js saveAudit()
ALTER TABLE public.audit_papan_audits
  ADD COLUMN IF NOT EXISTS audit_id     TEXT,
  ADD COLUMN IF NOT EXISTS batch_ref    BIGINT,
  ADD COLUMN IF NOT EXISTS nursery      TEXT,
  ADD COLUMN IF NOT EXISTS plot         TEXT,
  ADD COLUMN IF NOT EXISTS batch_no     TEXT,
  ADD COLUMN IF NOT EXISTS presence     TEXT,
  ADD COLUMN IF NOT EXISTS info_correct TEXT,
  ADD COLUMN IF NOT EXISTS condition    TEXT,
  ADD COLUMN IF NOT EXISTS remarks      TEXT,
  ADD COLUMN IF NOT EXISTS photo_url    TEXT,
  ADD COLUMN IF NOT EXISTS date         DATE,
  ADD COLUMN IF NOT EXISTS auditor_name TEXT;

-- Papan batches — audit_papan_script.js saveBatch()
ALTER TABLE public.audit_batches
  ADD COLUMN IF NOT EXISTS batch_id        TEXT,
  ADD COLUMN IF NOT EXISTS nursery         TEXT,
  ADD COLUMN IF NOT EXISTS plot            TEXT,
  ADD COLUMN IF NOT EXISTS batch_no        TEXT,
  ADD COLUMN IF NOT EXISTS breed           TEXT,
  ADD COLUMN IF NOT EXISTS qty_transplant  INTEGER,
  ADD COLUMN IF NOT EXISTS date_planted    DATE,
  ADD COLUMN IF NOT EXISTS date_transplant DATE,
  ADD COLUMN IF NOT EXISTS date_mature     DATE;

-- Maintenance tasks — read by audit_maintenance_script.js
ALTER TABLE public.audit_maintenance_tasks
  ADD COLUMN IF NOT EXISTS nursery        TEXT,
  ADD COLUMN IF NOT EXISTS plot           TEXT,
  ADD COLUMN IF NOT EXISTS task_type      TEXT,
  ADD COLUMN IF NOT EXISTS chemical       TEXT,
  ADD COLUMN IF NOT EXISTS round          TEXT,
  ADD COLUMN IF NOT EXISTS batch          TEXT,
  ADD COLUMN IF NOT EXISTS worker_name    TEXT,
  ADD COLUMN IF NOT EXISTS completed_date DATE,
  ADD COLUMN IF NOT EXISTS photo_urls     JSONB;

-- Maintenance audits — audit_maintenance_script.js saveAudit()
ALTER TABLE public.audit_maintenance_audits
  ADD COLUMN IF NOT EXISTS audit_id     TEXT,
  ADD COLUMN IF NOT EXISTS task_id      BIGINT,
  ADD COLUMN IF NOT EXISTS nursery      TEXT,
  ADD COLUMN IF NOT EXISTS plot         TEXT,
  ADD COLUMN IF NOT EXISTS task_type    TEXT,
  ADD COLUMN IF NOT EXISTS result       TEXT,
  ADD COLUMN IF NOT EXISTS remarks      TEXT,
  ADD COLUMN IF NOT EXISTS photo_url    TEXT,
  ADD COLUMN IF NOT EXISTS date         DATE,
  ADD COLUMN IF NOT EXISTS auditor_name TEXT;


-- ────────────────────────────────────────────────────────────────
-- 2. WHO MAY DO WHAT
--
--    Read / create / edit : any signed-in MJM account that is not a
--                           customer. This is the part that was broken —
--                           the old check also demanded an audit module
--                           permission that auditors were never given.
--    Delete               : admins only, as requested.
--
--    Note these are four separate policies, not one FOR ALL. Permissive
--    policies are OR-ed together, so a FOR ALL policy would hand DELETE
--    back to everyone and undo the admin restriction.
-- ────────────────────────────────────────────────────────────────

-- Is the caller a signed-in staff member (not a customer)?
CREATE OR REPLACE FUNCTION public._mjm_is_staff()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM shared_profiles p
     WHERE p.id = auth.uid()
       AND COALESCE(p.user_type, 'system') <> 'customer'
  );
$fn$;

-- Is the caller an audit admin?
CREATE OR REPLACE FUNCTION public._mjm_is_audit_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM shared_profiles p
     WHERE p.id = auth.uid()
       AND ( lower(COALESCE(p.role, '')) IN ('admin', 'administrator')
          OR (p.permissions -> 'modules' ->> 'audit') = 'admin' )
  );
$fn$;

REVOKE ALL ON FUNCTION public._mjm_is_staff()          FROM PUBLIC;
REVOKE ALL ON FUNCTION public._mjm_is_audit_admin()    FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public._mjm_is_staff()       TO authenticated;
GRANT EXECUTE ON FUNCTION public._mjm_is_audit_admin() TO authenticated;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'audit_plot_audits',
    'audit_height_records',
    'audit_papan_audits',
    'audit_batches',
    'audit_maintenance_tasks',
    'audit_maintenance_audits'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);

    -- Clear out every earlier attempt so re-running stays clean.
    EXECUTE format('DROP POLICY IF EXISTS "Authenticated full access" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_module_read"  ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_module_write" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_read"   ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_insert" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_update" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "audit_delete" ON public.%I', t);

    EXECUTE format('CREATE POLICY "audit_read" ON public.%I
                    FOR SELECT TO authenticated
                    USING (public._mjm_is_staff())', t);
    EXECUTE format('CREATE POLICY "audit_insert" ON public.%I
                    FOR INSERT TO authenticated
                    WITH CHECK (public._mjm_is_staff())', t);
    EXECUTE format('CREATE POLICY "audit_update" ON public.%I
                    FOR UPDATE TO authenticated
                    USING (public._mjm_is_staff())
                    WITH CHECK (public._mjm_is_staff())', t);
    EXECUTE format('CREATE POLICY "audit_delete" ON public.%I
                    FOR DELETE TO authenticated
                    USING (public._mjm_is_audit_admin())', t);
  END LOOP;
END $$;


-- ────────────────────────────────────────────────────────────────
-- 3. PHOTOS
--    The app uploads to the audit-photos bucket and then renders the
--    /object/public/ URL, so the bucket has to be public to read and
--    writable by signed-in staff.
-- ────────────────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('audit-photos', 'audit-photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "audit_photos_read"   ON storage.objects;
DROP POLICY IF EXISTS "audit_photos_insert" ON storage.objects;
DROP POLICY IF EXISTS "audit_photos_update" ON storage.objects;

CREATE POLICY "audit_photos_read" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'audit-photos');
CREATE POLICY "audit_photos_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'audit-photos');
CREATE POLICY "audit_photos_update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'audit-photos')
  WITH CHECK (bucket_id = 'audit-photos');

COMMIT;


-- ================================================================
-- CHECK — what the policies look like now, and how many rows each
-- table holds. Send this back if the app is still empty afterwards.
-- ================================================================
SELECT tablename, policyname, cmd, roles
FROM   pg_policies
WHERE  schemaname = 'public' AND tablename LIKE 'audit_%'
ORDER  BY tablename, cmd;

SELECT 'audit_plot_audits'        AS table_name, count(*) FROM public.audit_plot_audits
UNION ALL SELECT 'audit_height_records',     count(*) FROM public.audit_height_records
UNION ALL SELECT 'audit_papan_audits',       count(*) FROM public.audit_papan_audits
UNION ALL SELECT 'audit_batches',            count(*) FROM public.audit_batches
UNION ALL SELECT 'audit_maintenance_tasks',  count(*) FROM public.audit_maintenance_tasks
UNION ALL SELECT 'audit_maintenance_audits', count(*) FROM public.audit_maintenance_audits;
