-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_plot_status.sql
--
-- PLOT STATUS: daily plot condition reporting by Field Conductors.
--
--   1. nops_plot_status_stages  — the ordered "life stages" a plot moves
--        through (e.g. Soil Preparation → Polybag Ready → Transplanted →
--        Maturing → Open Collection → Cleared). Fully editable from the
--        settings inside the Life of Plot page — add/delete freely.
--        ideal_days = how many days a plot should ideally stay in this
--        stage before moving to the next one (used now for the day
--        counter, later for the over-time alert function).
--
--   2. nops_plot_status_entries — one row per plot per day, keyed in by
--        the FC on the FC Portal's Plot Status module. Same-day re-entry
--        updates the existing row (UNIQUE plot_name + entry_date).
--        Plots are the existing shared_plots (Seedling Stock Management
--        settings).
--
-- Per-user nursery visibility for the FC Portal module is stored on
-- shared_profiles.permissions JSONB (no DDL needed):
--   { "plot_status_nurseries": ["Nursery A", ...] }
--   key absent/null = user can see ALL nurseries' plot status.
--
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- ============================================================================

-- ────────────────────────────────────────────────────────────────
-- PART 1: Plot status stages
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_plot_status_stages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  sort_order  INT  NOT NULL DEFAULT 0,
  ideal_days  NUMERIC,      -- ideal days in this stage before the next one
  remark      TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nops_plot_status_stages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_status_stages'
       AND policyname='Authenticated read status stages'
  ) THEN
    CREATE POLICY "Authenticated read status stages" ON nops_plot_status_stages
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_status_stages'
       AND policyname='Authenticated write status stages'
  ) THEN
    CREATE POLICY "Authenticated write status stages" ON nops_plot_status_stages
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 2: Daily plot status entries (FC Portal)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_plot_status_entries (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_date    DATE NOT NULL,
  nursery_name  TEXT,
  plot_name     TEXT NOT NULL,               -- from shared_plots
  stage_id      BIGINT REFERENCES nops_plot_status_stages(id) ON DELETE SET NULL,
  stage_name    TEXT NOT NULL,               -- snapshot — history survives stage deletion
  remark        TEXT,
  reported_by   TEXT,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ,
  UNIQUE (plot_name, entry_date)             -- one status per plot per day
);

CREATE INDEX IF NOT EXISTS nops_plot_status_entries_plot_idx
  ON nops_plot_status_entries (plot_name, entry_date DESC);

ALTER TABLE nops_plot_status_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_status_entries'
       AND policyname='Authenticated read status entries'
  ) THEN
    CREATE POLICY "Authenticated read status entries" ON nops_plot_status_entries
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_status_entries'
       AND policyname='Authenticated write status entries'
  ) THEN
    CREATE POLICY "Authenticated write status entries" ON nops_plot_status_entries
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;
