-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_roles.sql
--
-- NELOS — roles inside a system, and routing per category.
--
-- Two things the section-level routing could not say:
--
--   1. "A Planting Discrepancy from the Stock system goes to Nursery
--      Operation, but a Stock Variance from the same system stays with
--      Stock." Routing was one rule per section; it is now one rule per
--      (section, category), with a section default underneath.
--
--   2. "The Admin Portal has two people. Some cases go to Admin 1, some to
--      Admin 2." A queue could only be a whole module, so there was no way
--      to name a seat inside it. A ROLE is that seat: handlers are pinned
--      to a system AND a role in it, and a routing rule may target the
--      role rather than the whole module.
--
-- HOW A NEW CASE IS ROUTED — first match wins:
--      1. a rule for exactly this (source_module, category)
--      2. the sections default rule (category IS NULL)
--      3. the section itself
--   An assigned_module set by the caller always wins over all three:
--   routing is the default, not a rule.
--
-- WHAT SOMEBODY SEES — unchanged except for the role step:
--      • their home modules queue, EXCEPT cases routed to a role that is
--        not theirs. A case with no role is the whole modules to take.
--      • plus anything assigned to them personally, in any queue, past
--        every filter.
--      • unpinned, or Nelos admin → everything.
--
-- nelos_modules.route_to is SUPERSEDED by nelos_routes and is migrated into
-- it as each sections default rule. The column is left in place so this
-- stays reversible, but nothing reads it any more — see PART 4.
--
-- Requires migration_nelos.sql, migration_nelos_modules.sql and
-- migration_nelos_routing.sql.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare relation does not exist. Requires: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_modules') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_modules" does not exist yet.',
      HINT    = 'Run migration_nelos_modules.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_handlers') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_handlers" does not exist yet.',
      HINT    = 'Run migration_nelos_routing.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: Roles — the seats inside a system
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_roles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key  TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,
  name        TEXT NOT NULL,          -- Admin 1, Senior Auditor, …
  sort_order  INT  NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT nelos_roles_name_not_blank CHECK (btrim(name) <> '')
);

-- Two seats with the same name in one system would be indistinguishable on
-- every screen, so they are refused. Case-insensitive: "Admin 1" and
-- "admin 1" are the same seat.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_roles_uniq
  ON nelos_roles (module_key, lower(name));

ALTER TABLE nelos_roles ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_roles'
       AND policyname='Authenticated read nelos roles') THEN
    CREATE POLICY "Authenticated read nelos roles" ON nelos_roles
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_roles'
       AND policyname='Authenticated write nelos roles') THEN
    CREATE POLICY "Authenticated write nelos roles" ON nelos_roles
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- No roles are seeded. A seat is a decision about how a team is organised,
-- and inventing "Admin 1"/"Admin 2" here would put words in the admins
-- mouth. Until roles exist, every rule targets a whole module, which is
-- exactly how routing behaved before this migration.

-- ────────────────────────────────────────────────────────────────
-- PART 2: A handler sits in a system AND a seat
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_handlers
  ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS nelos_handlers_role_idx ON nelos_handlers (role_id);

-- A role belongs to one module, so a handlers seat must be in the system
-- they are pinned to. Enforced in the app (the picker only offers that
-- modules roles); this cleans up anything left behind when somebody is
-- moved to a different system.
UPDATE nelos_handlers h
   SET role_id = NULL
  FROM nelos_roles r
 WHERE h.role_id = r.id
   AND h.primary_module IS DISTINCT FROM r.module_key;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Routing rules, per section and category
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_routes (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_module  TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,

  -- NULL = this sections default, used by any category without its own
  -- rule. Stored by name, like nelos_cases.category, so renaming a
  -- category in Settings never orphans a rule silently.
  category       TEXT,

  to_module      TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,
  to_role_id     BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL,

  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by     TEXT
);

-- One rule per category per section, and one default per section. Two
-- partial indexes rather than a plain UNIQUE, because Postgres treats NULLs
-- as distinct and would happily allow a second default row.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_routes_cat_uniq
  ON nelos_routes (source_module, category) WHERE category IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS nelos_routes_default_uniq
  ON nelos_routes (source_module) WHERE category IS NULL;

ALTER TABLE nelos_routes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_routes'
       AND policyname='Authenticated read nelos routes') THEN
    CREATE POLICY "Authenticated read nelos routes" ON nelos_routes
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_routes'
       AND policyname='Authenticated write nelos routes') THEN
    CREATE POLICY "Authenticated write nelos routes" ON nelos_routes
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Carry the old section-level routes across
--
-- Every section that had a route_to becomes a default rule here. Only
-- inserted where no default exists yet, so a re-run cannot undo an edit
-- made on the User Setting page.
-- ────────────────────────────────────────────────────────────────
INSERT INTO nelos_routes (source_module, category, to_module, updated_by)
SELECT m.key, NULL, m.route_to, 'system (migrated from nelos_modules.route_to)'
  FROM nelos_modules m
 WHERE m.route_to IS NOT NULL
   AND NOT EXISTS (
     SELECT 1 FROM nelos_routes r
      WHERE r.source_module = m.key AND r.category IS NULL
   );

-- ────────────────────────────────────────────────────────────────
-- PART 5: A case remembers which seat it was sent to
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_cases
  ADD COLUMN IF NOT EXISTS assigned_role_id BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS nelos_cases_role_idx ON nelos_cases (assigned_role_id);

-- Routing, now category-aware. Replaces the version in
-- migration_nelos_routing.sql; that files trigger is redefined here rather
-- than duplicated, so running the migrations in order leaves one rule.
-- ── Superseded by migration_nelos_seats.sql ─────────────────────
-- That file replaces named roles with a number inside each system, and
-- redefines this trigger and both scope functions to match. Re-running
-- THIS file afterwards would drop the newer functions and put the
-- role-shaped ones back, silently reverting the change — so when
-- nelos_handlers.seat_no exists, the later migration owns these objects
-- and this block stands down.
DO $guard$
BEGIN
IF EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema='public' AND table_name='nelos_handlers'
              AND column_name='seat_no') THEN
  RAISE NOTICE 'nelos_handlers.seat_no present — migration_nelos_seats.sql owns the routing trigger and scope functions; leaving them as they are.';
  RETURN;
END IF;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_route_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE r RECORD;
BEGIN
  -- An explicit destination wins: routing is the default, not a rule.
  IF NEW.assigned_module IS NOT NULL AND NEW.assigned_module <> '' THEN
    RETURN NEW;
  END IF;

  -- Exact category rule first, then the section default. ORDER BY puts the
  -- category rule ahead of the default, so one query settles it.
  SELECT nr.to_module, nr.to_role_id INTO r
    FROM nelos_routes nr
   WHERE nr.source_module = NEW.source_module
     AND (nr.category = NEW.category OR nr.category IS NULL)
   ORDER BY (nr.category IS NULL)          -- false (0) sorts before true (1)
   LIMIT 1;

  IF FOUND THEN
    NEW.assigned_module  := r.to_module;
    -- Only carry the seat when the caller has not named one already.
    IF NEW.assigned_role_id IS NULL THEN
      NEW.assigned_role_id := r.to_role_id;
    END IF;
  ELSE
    NEW.assigned_module := NEW.source_module;
  END IF;

  RETURN NEW;
END $$
$fn$;

EXECUTE $fn$
DROP TRIGGER IF EXISTS nelos_cases_route ON nelos_cases;
CREATE TRIGGER nelos_cases_route
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_route_case()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_my_scope()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_people()
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_my_scope()
RETURNS TABLE (primary_module TEXT, role_id BIGINT, categories TEXT[], is_admin BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.primary_module,
         h.role_id,
         h.categories,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin'
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE p.id = auth.uid()
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_my_scope() TO authenticated
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_people()
RETURNS TABLE (
  id             UUID,
  full_name      TEXT,
  email          TEXT,
  nelos_level    TEXT,
  primary_module TEXT,
  role_id        BIGINT,
  categories     TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id,
         p.full_name,
         p.email,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') AS nelos_level,
         h.primary_module,
         h.role_id,
         h.categories
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_people() TO authenticated
$fn$;
END $guard$;

-- ────────────────────────────────────────────────────────────────
-- PART 7: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT r.source_module AS raised_in,
       COALESCE(r.category, '(any other category)') AS for_category,
       r.to_module AS worked_by,
       COALESCE(ro.name, '(anyone in that module)') AS seat
  FROM nelos_routes r
  LEFT JOIN nelos_roles ro ON ro.id = r.to_role_id
  JOIN nelos_modules m ON m.key = r.source_module
 ORDER BY m.sort_order, (r.category IS NULL) DESC, r.category;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   ALTER TABLE nelos_cases    DROP COLUMN IF EXISTS assigned_role_id;
--   ALTER TABLE nelos_handlers DROP COLUMN IF EXISTS role_id;
--   DROP TABLE IF EXISTS nelos_routes, nelos_roles;
--   then re-run migration_nelos_routing.sql to restore its trigger and
--   the two-column nelos_my_scope()/nelos_people(). nelos_modules.route_to
--   was never cleared, so the old section routing comes back with it.
