-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_plot_rounds.sql
--
-- PLOT ROUNDS: one row per production cycle of a plot (a full cycle
-- usually takes ~12 months). Powers the Life of Plot page's grouped
-- timeline: completed rounds collapse to a title, the current round
-- shows expanded with all its work details.
--
-- Work records are assigned to rounds BY DATE (a work belongs to the
-- latest round whose started_on is on/before the work's date), so no
-- change is needed anywhere works are created. A plot with no rounds
-- row yet is treated as being in an implicit current Round 1.
--
-- "Complete Round" on the Life of Plot page closes the current round
-- (sets closed_on) and opens the next one.
--
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- ============================================================================

CREATE TABLE IF NOT EXISTS nops_plot_rounds (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot_name   TEXT NOT NULL,               -- from shared_plots
  round_no    INT  NOT NULL,
  started_on  DATE NOT NULL,
  closed_on   DATE,                        -- NULL = current round
  remark      TEXT,
  created_by  TEXT,
  created_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE (plot_name, round_no)
);

CREATE INDEX IF NOT EXISTS nops_plot_rounds_plot_idx
  ON nops_plot_rounds (plot_name, round_no DESC);

ALTER TABLE nops_plot_rounds ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_rounds'
       AND policyname='Authenticated read plot rounds'
  ) THEN
    CREATE POLICY "Authenticated read plot rounds" ON nops_plot_rounds
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_rounds'
       AND policyname='Authenticated write plot rounds'
  ) THEN
    CREATE POLICY "Authenticated write plot rounds" ON nops_plot_rounds
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;
