-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_modules.sql
--
-- NELOS — User Setting: who handles which modules cases.
--
-- Nursery Case Log is linked to several modules. A case raised anywhere
-- lands in that modules block. This migration adds the two tables the
-- User Setting page is built on:
--
--   1. nelos_modules         — the linked modules themselves. A row per
--                              block on the User Setting page. Editable,
--                              so a sixth module is a row rather than a
--                              deploy.
--   2. nelos_module_members  — who handles each modules cases, by email,
--                              and (optionally) which categories they may
--                              see.
--
-- HOW VISIBILITY WORKS — the rule matters, so it is written down once here
-- and implemented once in shared/shared_nelos.js:
--
--   • Nobody has a membership row yet  → they see every case.
--     This is deliberate. Turning the feature on must not blank out the
--     case list for the whole company on day one, and it matches how
--     shared_access.js already treats an unset permission ("a missing key
--     means allowed").
--   • They have at least one membership row → they see cases from those
--     modules only, and within each module only the categories that row
--     allows (an empty/NULL categories array means "all categories in
--     this module").
--   • Nelos admins (permissions.modules.nelos = admin) always see
--     everything, whatever their rows say. Without this an admin could
--     lock themselves out of their own case log.
--
-- Requires migration_nelos.sql to have been run first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare relation does not exist. Requires: migration_nelos.sql.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: The linked modules
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_modules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,   -- matches nelos_cases.source_module
  label       TEXT NOT NULL,          -- what the block is called on screen
  icon        TEXT,
  href        TEXT,                   -- where the module lives, from /nelos/
  sort_order  INT  NOT NULL DEFAULT 0,
  active      BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nelos_modules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_modules'
       AND policyname='Authenticated read nelos modules'
  ) THEN
    CREATE POLICY "Authenticated read nelos modules" ON nelos_modules
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_modules'
       AND policyname='Authenticated write nelos modules'
  ) THEN
    CREATE POLICY "Authenticated write nelos modules" ON nelos_modules
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- The five modules the case log is linked to today.
--
-- `key` is the value written into nelos_cases.source_module, so these must
-- match the module keys the rest of the portal already uses:
--   operation   — Nursery Seedling Stock Management ("AI Stock System")
--   nursery_ops — Nursery Operation Management
--   scan        — the FC Portal (scan.mjmnursery.com)
--   mobile      — the Mobile app ("Admin Portal")
--   audit       — Nursery Audit ("Auditor Portal")
--
-- ON CONFLICT DO NOTHING so a re-run never undoes a label somebody edited.
INSERT INTO nelos_modules (key, label, icon, href, sort_order) VALUES
  ('operation',   'AI Stock System',    '🌱', '../operation/operation_dashboard.html',     10),
  ('nursery_ops', 'Nursery Operation',  '🌿', '../nursery_ops/nursery_ops_dashboard.html', 20),
  ('scan',        'FC Portal',          '📱', 'https://scan.mjmnursery.com',               30),
  ('mobile',      'Admin Portal',       '🗂️', '../mobile/mobile_landing.html',             40),
  ('audit',       'Auditor Portal',     '📋', '../audit/audit_home.html',                  50)
ON CONFLICT (key) DO NOTHING;

-- Label corrections, applied only where the row still carries the label this
-- file originally seeded. A label somebody has since edited on the User
-- Setting page is left alone — this fixes the default, it does not stomp a
-- decision.
UPDATE nelos_modules SET label = 'Seedling Stock System'
 WHERE key = 'operation' AND label = 'AI Stock System';
UPDATE nelos_modules SET label = 'Audit Portal'
 WHERE key = 'audit'     AND label = 'Auditor Portal';

-- ── Renaming a module KEY (read before you try it) ──────────────
-- `label` is display only — rename it freely, on this page or here.
-- `key` is an identifier, and three other things carry a copy of it:
--
--   1. nelos_cases.source_module   — every case already filed
--   2. nelos_module_members.module_key — handled by ON UPDATE CASCADE below
--   3. four hardcoded call sites that raise or filter cases:
--        operation/operation_batch_detail.html   source: operation
--        operation/operation_dashboard.html      source: operation
--        nursery_ops/nursery_ops_dashboard.html  source: nursery_ops
--        audit/audit_admin.html                  source: audit
--      plus the SOURCE_LABEL fallback map in shared/shared_nelos.js
--
-- So a key rename is a code change AND a data change, and doing only one
-- of them silently orphans cases: they keep the old source_module, stop
-- matching any block, and vanish from the To-Do lists. To rename a key,
-- change the call sites first, then run BOTH statements together:
--
--   UPDATE nelos_modules SET key = new_key WHERE key = old_key;
--   UPDATE nelos_cases SET source_module = new_key WHERE source_module = old_key;
--
-- The member rows follow on their own.
--
-- The keys shipped here deliberately match the table prefixes the rest of
-- the portal already uses (operation_, nops_, audit_…), which is what the
-- grey chip under each block name is showing.

-- (The constraint that makes a key rename carry its member rows is set up
--  in PART 2, once nelos_module_members exists.)

-- ────────────────────────────────────────────────────────────────
-- PART 2: Who handles each modules cases
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_module_members (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key  TEXT NOT NULL REFERENCES nelos_modules(key) ON DELETE CASCADE,

  -- Email is the handle, because that is what an admin types and because a
  -- person can be added before they have ever signed in. user_id is filled
  -- in when the email matches a shared_profiles row, and is what the app
  -- actually matches on once it is known.
  email       TEXT NOT NULL,
  user_id     UUID REFERENCES shared_profiles(id) ON DELETE CASCADE,
  full_name   TEXT,

  -- Which case categories this person may see in this module.
  -- NULL or empty = every category. Values are nelos_categories.name.
  categories  TEXT[],

  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by  TEXT
);

-- One row per person per module. Case-insensitive, so adding
-- "Ali@mjm.com" twice in different case cannot make two rows.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_module_members_uniq
  ON nelos_module_members (module_key, lower(email));
CREATE INDEX IF NOT EXISTS nelos_module_members_user_idx
  ON nelos_module_members (user_id);
CREATE INDEX IF NOT EXISTS nelos_module_members_email_idx
  ON nelos_module_members (lower(email));

-- Let a key rename carry its member rows with it, instead of failing on the
-- foreign key. The table above may have been created by an earlier run of
-- this file, when the constraint was still ON DELETE only, so this upgrades
-- it in place. Guarded on confupdtype so re-running does not churn it.
DO $$
DECLARE c TEXT;
BEGIN
  SELECT conname INTO c
    FROM pg_constraint
   WHERE conrelid  = 'public.nelos_module_members'::regclass
     AND contype   = 'f'
     AND confrelid = 'public.nelos_modules'::regclass
     AND confupdtype <> 'c';          -- c = already ON UPDATE CASCADE
  IF c IS NOT NULL THEN
    EXECUTE format('ALTER TABLE nelos_module_members DROP CONSTRAINT %I', c);
    ALTER TABLE nelos_module_members
      ADD CONSTRAINT nelos_module_members_module_key_fkey
      FOREIGN KEY (module_key) REFERENCES nelos_modules(key)
      ON UPDATE CASCADE ON DELETE CASCADE;
    RAISE NOTICE 'nelos_module_members.module_key now cascades on rename.';
  END IF;
END $$;

ALTER TABLE nelos_module_members ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_module_members'
       AND policyname='Authenticated read nelos members'
  ) THEN
    CREATE POLICY "Authenticated read nelos members" ON nelos_module_members
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_module_members'
       AND policyname='Authenticated write nelos members'
  ) THEN
    CREATE POLICY "Authenticated write nelos members" ON nelos_module_members
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Looking somebody up by email
--
-- The User Setting page takes a typed email and needs the matching profile
-- so the member row can carry a user_id and a real name. shared_profiles
-- is readable only for your own row unless you hold manage_users, so this
-- goes through a SECURITY DEFINER function that returns three columns and
-- nothing else — the permissions blob stays unreadable.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_lookup_user(p_email TEXT)
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE lower(p.email) = lower(trim(p_email))
   LIMIT 1
$$;

GRANT EXECUTE ON FUNCTION public.nelos_lookup_user(TEXT) TO authenticated;

-- Everybody in the system, for the "add someone" dropdown on the User
-- Setting page — so an admin picks a colleague instead of typing an address
-- from memory and mistyping it.
--
-- SECURITY DEFINER reads past the shared_profiles policy, so this checks
-- for itself who is asking and returns NOTHING to anybody who is not a
-- Nelos admin or a portal user-manager. That is the same test the User
-- Setting page gates on, so the function cannot become a way for an
-- ordinary account to enumerate everyones email address.
CREATE OR REPLACE FUNCTION public.nelos_directory()
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE p.email IS NOT NULL
     AND p.email <> ''
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$;

GRANT EXECUTE ON FUNCTION public.nelos_directory() TO authenticated;

-- Back-fill user_id on any member row added before that person signed up.
-- Cheap, and it means an admin never has to re-add somebody.
UPDATE nelos_module_members m
   SET user_id   = p.id,
       full_name = COALESCE(m.full_name, p.full_name)
  FROM public.shared_profiles p
 WHERE m.user_id IS NULL
   AND lower(p.email) = lower(m.email);

-- ────────────────────────────────────────────────────────────────
-- PART 4: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT m.key, m.label, count(mm.id) AS members
  FROM nelos_modules m
  LEFT JOIN nelos_module_members mm ON mm.module_key = m.key
 GROUP BY m.key, m.label, m.sort_order
 ORDER BY m.sort_order;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP FUNCTION IF EXISTS public.nelos_lookup_user(TEXT);
--   DROP TABLE IF EXISTS nelos_module_members, nelos_modules;
