-- ============================================================================
-- Splitting a plot on the map
-- shared/migration_plot_areas.sql
--
-- WHY
--
-- shared_plots.map_top holds ONE polygon per plot, which assumes a plot is one
-- thing. It often is not: a plot can be carrying two batches, planted weeks
-- apart, and then it has two stages running at once — half of it on Culling
-- while the other half is still on Tunggu buat culling. One polygon can only
-- be one colour, so the map has been telling half a truth.
--
-- PALMS has always modelled this. Its unit key is the plot while it is whole
-- ("B2") and "B2#A", "B2#B" once split — the field app logs against the area,
-- and shared_palms.js reads it. What was missing was anywhere to say WHERE on
-- the map area A is. This table is that.
--
--   plot_name  the plot, as in shared_plots.plot_name        e.g. B2
--   area_key   the letter after the # in the PALMS unit key  e.g. A
--   polygon    JSON [{x,y},…] in PERCENT of the nursery photo, exactly the
--              format shared_plots.map_top already uses, so one renderer
--              draws both
--   batch_name the batch standing in this area, pinned by the office from
--              shared_plot_batch_balance. Nullable: an area can be drawn
--              before anybody knows which batch is in it.
--
-- A plot with no rows here is undivided and keeps drawing from map_top. That
-- is the normal case and nothing has to be migrated.
--
-- Run in the Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.nops_plot_areas (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot_name   TEXT        NOT NULL,
  area_key    TEXT        NOT NULL,
  polygon     TEXT        NOT NULL,
  batch_name  TEXT,
  updated_by  TEXT,
  updated_at  TIMESTAMPTZ DEFAULT now(),
  created_at  TIMESTAMPTZ DEFAULT now(),
  -- One row per area of a plot. Re-drawing area A updates it rather than
  -- leaving two shapes both claiming to be A.
  CONSTRAINT nops_plot_areas_unique UNIQUE (plot_name, area_key)
);

CREATE INDEX IF NOT EXISTS nops_plot_areas_plot_idx
  ON public.nops_plot_areas (plot_name);

ALTER TABLE public.nops_plot_areas ENABLE ROW LEVEL SECURITY;

-- Same rule as the rest of PALMS: anyone holding the portal reads, admins
-- change. Redrawing a boundary re-describes the nursery for everybody, so it
-- is not something a normal account does by accident.
--
-- palms_has_access() and palms_is_admin() come from migration_palms_rls.sql.
-- If that has not been run this block does nothing and the table stays
-- readable only to whoever the default policy lets in — which is nobody.
DO $areas$
BEGIN
  -- to_regprocedure, not to_regproc: to_regproc takes a bare NAME and returns
  -- NULL for anything with parentheses in it, so the obvious-looking
  -- to_regproc(…()) is always NULL and this guard would skip the policies
  -- on a database that has the function.
  IF to_regprocedure('public.palms_has_access()') IS NULL THEN
    RAISE NOTICE 'palms_has_access() not found — run migration_palms_rls.sql first, then re-run this file.';
    RETURN;
  END IF;

  EXECUTE 'DROP POLICY IF EXISTS "plot areas read"  ON public.nops_plot_areas';
  EXECUTE 'DROP POLICY IF EXISTS "plot areas write" ON public.nops_plot_areas';

  EXECUTE 'CREATE POLICY "plot areas read" ON public.nops_plot_areas
             FOR SELECT TO authenticated USING (public.palms_has_access())';
  EXECUTE 'CREATE POLICY "plot areas write" ON public.nops_plot_areas
             FOR ALL TO authenticated
             USING (public.palms_is_admin()) WITH CHECK (public.palms_is_admin())';
END
$areas$;

-- Should list two policies, neither of them a bare "true".
SELECT policyname, cmd, qual AS using_clause, with_check
FROM   pg_policies
WHERE  schemaname = 'public' AND tablename = 'nops_plot_areas'
ORDER  BY policyname;


/* ── TO UNDO ──
   Every plot goes back to its single map_top polygon. Areas already logged
   against in PALMS ("B2#A") keep their history — the log is a different
   table — they simply stop being drawn separately.

   DROP TABLE IF EXISTS public.nops_plot_areas;
*/
