-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos.sql
--
-- New module: NELOS — Nursery Carlos (nelos_*)
--
-- Nelos is the one place a case lives. Any module can raise a case; every
-- module shows the ones still pending; the case itself is only ever worked
-- on here. Before Nelos, `operation_follow_up_cases` was the only case-like
-- table and only Batch Detail ever wrote to it — nobody had a list of what
-- was outstanding, so cases were raised and then lost.
--
--   1. nelos_categories     — the kinds of case there are (Planting
--                             Discrepancy, Height Shortfall, Pest, …).
--                             Editable from the modules Settings; nothing
--                             is hard-coded, the same way nops_work_types
--                             works for Nursery Operation.
--   2. nelos_cases          — one row per case. Carries WHERE it came from
--                             (source_module + source_ref, so a case can
--                             link back to the exact page that raised it)
--                             and WHAT it is about (nursery / plot / batch,
--                             all optional — a case need not be about any
--                             of them).
--   3. nelos_case_comments  — the thread on a case. Status changes are
--                             written here too, so the history reads as one
--                             list rather than being split across tables.
--
-- Module access: permissions.modules.nelos = admin|normal|none,
-- granted on the main portals User Access (JSONB — no DDL needed).
-- What somebody sees once inside is decided by which linked modules and
-- categories they are set up for — see migration_nelos_modules.sql and
-- nelos/nelos_user_setting.html.
--
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────
-- PART 1: Case categories
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_categories (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT NOT NULL UNIQUE,
  sort_order        INT  NOT NULL DEFAULT 0,
  default_priority  TEXT NOT NULL DEFAULT 'normal',   -- low | normal | high | urgent
  default_days      INT,          -- due date = raised date + this, when set
  active            BOOLEAN NOT NULL DEFAULT true,
  remark            TEXT,
  created_at        TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nelos_categories ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_categories'
       AND policyname='Authenticated read nelos categories'
  ) THEN
    CREATE POLICY "Authenticated read nelos categories" ON nelos_categories
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_categories'
       AND policyname='Authenticated write nelos categories'
  ) THEN
    CREATE POLICY "Authenticated write nelos categories" ON nelos_categories
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Seed the case titles we already know about. Matching on the name means a
-- re-run never resurrects one an admin renamed or retired.
--
-- NOT EXISTS rather than ON CONFLICT (name): a later migration scopes a case
-- title to one system and replaces the global unique on name with a
-- per-system one, at which point ON CONFLICT (name) has no constraint to
-- match and a re-run of this file would fail outright.
INSERT INTO nelos_categories (name, sort_order, default_priority, default_days)
SELECT v.name, v.so, v.pri, v.days
  FROM (VALUES
    ('Planting Discrepancy', 10, 'high',   3),
    ('Height Shortfall',     20, 'normal', 7),
    ('Stock Variance',       30, 'high',   3),
    ('Pest / Disease',       40, 'urgent', 1),
    ('Maintenance Overdue',  50, 'normal', 7),
    ('Delivery Issue',       60, 'high',   2),
    ('Other',                90, 'normal', NULL)
  ) AS v(name, so, pri, days)
 WHERE NOT EXISTS (
   SELECT 1 FROM nelos_categories c WHERE lower(c.name) = lower(v.name)
 );

-- ────────────────────────────────────────────────────────────────
-- PART 2: Cases
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_cases (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_no        TEXT UNIQUE,        -- NLS-0001, assigned by trigger below
  title          TEXT NOT NULL,
  description    TEXT,
  category       TEXT,               -- nelos_categories.name, by value not FK
                                     -- so renaming a category never orphans
                                     -- a closed cases history
  priority       TEXT NOT NULL DEFAULT 'normal',  -- low | normal | high | urgent
  status         TEXT NOT NULL DEFAULT 'open',    -- open | in_progress | resolved | closed

  -- Where it came from. source_module is what the To-Do widgets filter on;
  -- source_ref is a link back to the exact page that raised it, written as
  -- seen from a module folder — i.e. starting ../, because the only page
  -- that follows it is nelos/nelos_case.html
  -- (e.g. ../operation/operation_batch_detail.html?batch=264).
  source_module  TEXT NOT NULL DEFAULT 'nelos',   -- operation | audit | scan | nursery_ops | nelos
  source_ref     TEXT,

  -- What it is about. All optional — a case can be about the whole nursery,
  -- one plot, one batch, or nothing physical at all.
  nursery_name   TEXT,
  plot_name      TEXT,
  batch_name     TEXT,

  -- Who owns it. A case is assigned to a person, and that person (or a Nelos
  -- admin) closes it.
  assignee_id    UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  assignee_name  TEXT,               -- denormalised so the list renders without
                                     -- reading shared_profiles, which normal
                                     -- users may not select from
  due_date       DATE,

  raised_by      TEXT,
  raised_by_id   UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by     TEXT,
  updated_at     TIMESTAMPTZ,

  resolution     TEXT,               -- what was actually done
  resolved_by    TEXT,
  resolved_at    TIMESTAMPTZ,
  closed_by      TEXT,
  closed_at      TIMESTAMPTZ,

  CONSTRAINT nelos_cases_status_chk
    CHECK (status IN ('open','in_progress','resolved','closed')),
  CONSTRAINT nelos_cases_priority_chk
    CHECK (priority IN ('low','normal','high','urgent'))
);

-- The To-Do list is "pending cases, worst first" — this partial index is the
-- one every dashboard widget hits.
CREATE INDEX IF NOT EXISTS nelos_cases_pending_idx
  ON nelos_cases (priority, due_date NULLS LAST, created_at)
  WHERE status IN ('open','in_progress');
CREATE INDEX IF NOT EXISTS nelos_cases_assignee_idx ON nelos_cases (assignee_id, status);
CREATE INDEX IF NOT EXISTS nelos_cases_source_idx   ON nelos_cases (source_module, status);
CREATE INDEX IF NOT EXISTS nelos_cases_plot_idx     ON nelos_cases (plot_name);
CREATE INDEX IF NOT EXISTS nelos_cases_batch_idx    ON nelos_cases (batch_name);

-- Human case number. A sequence rather than count(*)+1 so two people raising
-- a case in the same second cannot land on the same number.
CREATE SEQUENCE IF NOT EXISTS nelos_case_no_seq START 1;

CREATE OR REPLACE FUNCTION public.nelos_assign_case_no()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.case_no IS NULL OR NEW.case_no = '' THEN
    NEW.case_no := 'NLS-' || LPAD(nextval('nelos_case_no_seq')::text, 4, '0');
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS nelos_cases_case_no ON nelos_cases;
CREATE TRIGGER nelos_cases_case_no
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_assign_case_no();

ALTER TABLE nelos_cases ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_cases'
       AND policyname='Authenticated read nelos cases'
  ) THEN
    CREATE POLICY "Authenticated read nelos cases" ON nelos_cases
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_cases'
       AND policyname='Authenticated write nelos cases'
  ) THEN
    CREATE POLICY "Authenticated write nelos cases" ON nelos_cases
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Case comments (and the status-change trail)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_case_comments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id      BIGINT NOT NULL REFERENCES nelos_cases(id) ON DELETE CASCADE,
  body         TEXT NOT NULL,
  kind         TEXT NOT NULL DEFAULT 'comment',  -- comment | status | assign
  author_name  TEXT,
  author_id    UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nelos_case_comments_case_idx
  ON nelos_case_comments (case_id, created_at);

ALTER TABLE nelos_case_comments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_case_comments'
       AND policyname='Authenticated read nelos comments'
  ) THEN
    CREATE POLICY "Authenticated read nelos comments" ON nelos_case_comments
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_case_comments'
       AND policyname='Authenticated write nelos comments'
  ) THEN
    CREATE POLICY "Authenticated write nelos comments" ON nelos_case_comments
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Who a case may be assigned to
--
-- shared_profiles is readable only for your OWN row unless you hold
-- manage_users (see migration_access_and_reviews.sql), so the assignee
-- picker cannot simply select from it. This SECURITY DEFINER function
-- returns the three columns the picker needs and nothing else — the
-- permissions blob stays unreadable. Only people who actually hold Nelos
-- are listed, so a case cannot be assigned to somebody who could never
-- open it.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_assignable_users()
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$;

GRANT EXECUTE ON FUNCTION public.nelos_assignable_users() TO authenticated;

-- ────────────────────────────────────────────────────────────────
-- PART 5: Absorb the old operation_follow_up_cases
--
-- Batch Detail used to insert { batch_name, issue_type, status } and
-- nothing else — there was no UI to read them back. Those rows become
-- Nelos cases so the backlog is visible on day one. The old table is
-- LEFT IN PLACE (not dropped) so this migration stays reversible; nothing
-- writes to it any more once operation_batch_detail.html is deployed.
--
-- Guarded by to_regclass: on a database where the table was never created
-- this whole block is skipped rather than erroring.
-- ────────────────────────────────────────────────────────────────
DO $$
DECLARE
  moved INT := 0;
BEGIN
  IF to_regclass('public.operation_follow_up_cases') IS NULL THEN
    RAISE NOTICE 'operation_follow_up_cases does not exist — nothing to absorb.';
    RETURN;
  END IF;

  INSERT INTO nelos_cases (
    title, description, category, priority, status,
    source_module, source_ref, batch_name, raised_by, created_at
  )
  SELECT
    COALESCE(f.issue_type, 'Follow-up') || ' — batch ' || COALESCE(f.batch_name, '?'),
    'Migrated from operation_follow_up_cases (raised by Batch Detail before Nelos existed).',
    COALESCE(f.issue_type, 'Other'),
    'high',
    -- "Pending Investigation" was the only status the old code ever wrote.
    CASE WHEN f.status ILIKE 'pending%' OR f.status IS NULL THEN 'open' ELSE 'closed' END,
    'operation',
    '../operation/operation_batch_detail.html?batch=' || COALESCE(f.batch_name, ''),
    f.batch_name,
    'system (migrated)',
    -- operation_follow_up_cases was created outside this repo, so its exact
    -- columns are not known here. Reading created_at through to_jsonb means
    -- a table without that column yields NULL instead of failing the whole
    -- migration on an unresolved reference.
    COALESCE((to_jsonb(f)->>'created_at')::timestamptz, now())
  FROM public.operation_follow_up_cases f
  -- Re-runnable: skip anything already brought across.
  WHERE NOT EXISTS (
    SELECT 1 FROM nelos_cases c
     WHERE c.source_module = 'operation'
       AND c.batch_name IS NOT DISTINCT FROM f.batch_name
       AND c.category    IS NOT DISTINCT FROM COALESCE(f.issue_type, 'Other')
       AND c.raised_by   = 'system (migrated)'
  );

  GET DIAGNOSTICS moved = ROW_COUNT;
  RAISE NOTICE 'Absorbed % follow-up case(s) into nelos_cases.', moved;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 6: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT 'nelos_categories'    AS table_name, count(*) AS rows FROM nelos_categories
UNION ALL
SELECT 'nelos_cases',              count(*) FROM nelos_cases
UNION ALL
SELECT 'nelos_cases (pending)',    count(*) FROM nelos_cases WHERE status IN ('open','in_progress')
UNION ALL
SELECT 'nelos_case_comments',      count(*) FROM nelos_case_comments;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP FUNCTION IF EXISTS public.nelos_assignable_users();
--   DROP TABLE IF EXISTS nelos_case_comments, nelos_cases, nelos_categories;
--   DROP FUNCTION IF EXISTS public.nelos_assign_case_no();
--   DROP SEQUENCE IF EXISTS nelos_case_no_seq;
-- operation_follow_up_cases is untouched by this migration, so reverting
-- Batch Details insert target is all that is needed to go back.
