-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_automation.sql
--
-- NELOS — work that repeats, raised on schedule.
--
-- Some cases are not raised because something went wrong. They are raised
-- because it is Monday, or because it is the first of the month: walk the
-- plots and record their condition, measure the seedlings, check the papan
-- tanda. Somebody has been remembering to open Nelos and type those in.
--
-- An automation is that standing instruction written down once:
--
--     what        a work type — plot condition, seedling height, papan tanda
--     where       a nursery, and a plot or all of them
--     who         which system deals with it, and which numbered handler
--     how often   every week, or every month, on a chosen day
--
-- and from then on Nelos raises the case itself.
--
-- HOW IT ACTUALLY FIRES
--   nelos_run_automations() raises whatever is due and moves each schedule
--   on. The Nelos page calls it when it loads, which is enough on its own:
--   somebody opens Nelos most days, and a case raised late is still raised.
--   For it to fire with nobody watching, schedule the same function — the
--   Supabase dashboards Integrations → Cron, once a day, is the whole
--   setup:
--
--     select cron.schedule(nelos-automations, 0 1 * * *,
--                          $$ select public.nelos_run_automations() $$);
--
--   It is safe either way. Due-ness is a date on the row, and raising
--   advances it, so calling it fifty times in one day raises one case.
--
-- THE LINK BACK TO THE AUDITOR PORTAL
--   Each work type knows which Auditor Portal module records it, and every
--   case carries source_ref — a deep link straight to that module, on that
--   plot (audit_deeplink.js has understood ?nursery=&plot= since the to-do
--   circles). So the auditor opens the case, presses through to the module,
--   does the audit where the audit belongs, and comes back to solve it. The
--   case does not copy the audit; it points at where it is done.
--
-- Requires the earlier nelos migrations — run migration_nelos_all.sql first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos tables do not exist yet.',
      HINT    = 'Run migration_nelos_all.sql first, then this file.';
  END IF;
END $preflight$;

-- ────────────────────────────────────────────────────────────────
-- PART 1: The work types
--
-- A table rather than a CHECK constraint, because this list grows: adding
-- a fourth kind of recurring audit should be one INSERT, not a migration
-- that rewrites a constraint and a dropdown.
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_work_types (
  key          TEXT PRIMARY KEY,
  label        TEXT NOT NULL,
  icon         TEXT,
  -- The Auditor Portal page that records this, as seen from nelos/. It is
  -- written with ../ because nelos/nelos_case.html is what follows it.
  audit_href   TEXT,
  title_tpl    TEXT NOT NULL,     -- {plot} and {nursery} are filled in
  default_priority TEXT NOT NULL DEFAULT 'normal',
  default_days INT  NOT NULL DEFAULT 7,
  sort_order   INT  NOT NULL DEFAULT 100,
  active       BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO nelos_work_types (key, label, icon, audit_href, title_tpl, default_priority, default_days, sort_order)
SELECT v.key, v.label, v.icon, v.href, v.tpl, v.pri, v.days, v.so
  FROM (VALUES
    ('plot_condition', 'Plot Condition',  '🌿', '../audit/audit_plot_audit.html',
     'Audit plot condition at plot "{plot}"',        'normal', 7,  10),
    ('seedling_height','Seedling Height', '📏', '../audit/audit_height_index.html',
     'Measure seedling height at plot "{plot}"',     'normal', 7,  20),
    ('papan_tanda',    'Papan Tanda',     '🪧', '../audit/audit_papan_index.html',
     'Check papan tanda at plot "{plot}"',           'normal', 7,  30),
    ('maintenance',    'Maintenance',     '🧰', '../audit/audit_maintenance_index.html',
     'Maintenance audit at plot "{plot}"',           'normal', 7,  40)
  ) AS v(key, label, icon, href, tpl, pri, days, so)
 WHERE NOT EXISTS (SELECT 1 FROM nelos_work_types w WHERE w.key = v.key);

-- ────────────────────────────────────────────────────────────────
-- PART 2: The standing instructions
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_automations (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_type     TEXT NOT NULL REFERENCES nelos_work_types(key) ON UPDATE CASCADE,

  -- Where. plot_name NULL means every plot in the nursery, and that is the
  -- common case: "measure every plot in Nursery 1 monthly" is one row, not
  -- fifty-two.
  nursery_name  TEXT NOT NULL,
  plot_name     TEXT,

  -- Who deals with it. Same two questions the New Case drawer asks.
  to_module     TEXT REFERENCES nelos_modules(key) ON UPDATE CASCADE,
  to_seat_no    INT,
  assignee_id   UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  assignee_name TEXT,

  -- How often. weekly → on_day is 0–6, Sunday first, matching extract(dow).
  --            monthly → on_day is 1–28, capped so February always has one.
  repeat_every  TEXT NOT NULL DEFAULT 'monthly',
  on_day        INT  NOT NULL DEFAULT 1,

  priority      TEXT NOT NULL DEFAULT 'normal',
  due_days      INT  NOT NULL DEFAULT 7,
  note          TEXT,

  active        BOOLEAN NOT NULL DEFAULT true,
  next_run_on   DATE NOT NULL DEFAULT CURRENT_DATE,
  last_run_on   DATE,
  last_raised   INT NOT NULL DEFAULT 0,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by    TEXT,
  updated_at    TIMESTAMPTZ,
  updated_by    TEXT,

  CONSTRAINT nelos_automations_repeat_chk CHECK (repeat_every IN ('weekly', 'monthly')),
  CONSTRAINT nelos_automations_day_chk    CHECK (on_day BETWEEN 0 AND 28),
  CONSTRAINT nelos_automations_pri_chk    CHECK (priority IN ('low','normal','high','urgent'))
);

CREATE INDEX IF NOT EXISTS nelos_automations_due_idx
  ON nelos_automations (next_run_on) WHERE active;

-- Which automation raised a case, so a repeat can tell whether the last one
-- is still open and not pile a second on top of it.
ALTER TABLE nelos_cases
  ADD COLUMN IF NOT EXISTS automation_id BIGINT REFERENCES nelos_automations(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS nelos_cases_automation_idx ON nelos_cases (automation_id);

-- ────────────────────────────────────────────────────────────────
-- PART 3: When is it next due
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_next_run(p_from DATE, p_every TEXT, p_day INT)
RETURNS DATE
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  d DATE;
BEGIN
  IF p_every = 'weekly' THEN
    -- The next p_day (0 = Sunday) strictly after p_from, so a run today
    -- schedules next week rather than looping on the same date.
    d := p_from + (((p_day - EXTRACT(dow FROM p_from)::int) + 7 - 1) % 7 + 1);
    RETURN d;
  END IF;

  -- Monthly: the chosen day of next month. Days are capped at 28 by the
  -- tables constraint, so there is no month this cannot land in.
  d := date_trunc('month', p_from)::date + INTERVAL '1 month';
  RETURN (date_trunc('month', d)::date + (LEAST(GREATEST(p_day, 1), 28) - 1));
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Raise whatever is due
--
-- SECURITY DEFINER: it writes cases on behalf of a schedule rather than a
-- person, and has to work the same whether it was called by the page or by
-- cron with no session at all.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_run_automations()
RETURNS TABLE (automation_id BIGINT, raised INT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  a         RECORD;
  w         RECORD;
  plot      TEXT;
  made      INT;
  case_title TEXT;
BEGIN
  FOR a IN
    SELECT * FROM nelos_automations
     WHERE active AND next_run_on <= CURRENT_DATE
     ORDER BY id
     FOR UPDATE SKIP LOCKED          -- two callers at once raise one case
  LOOP
    SELECT * INTO w FROM nelos_work_types WHERE key = a.work_type;
    made := 0;

    FOR plot IN
      SELECT CASE WHEN a.plot_name IS NOT NULL THEN a.plot_name ELSE p.plot_name END
        FROM (SELECT 1) AS one
        LEFT JOIN shared_plots p
               ON a.plot_name IS NULL AND p.nursery_name = a.nursery_name
       WHERE a.plot_name IS NOT NULL OR p.plot_name IS NOT NULL
    LOOP
      -- Last times case still open? Then this plot is not behind on the
      -- work, it is behind on somebody doing it, and a second case says
      -- nothing the first did not.
      IF EXISTS (
        SELECT 1 FROM nelos_cases c
         WHERE c.automation_id = a.id
           AND c.plot_name IS NOT DISTINCT FROM plot
           AND c.status IN ('open', 'in_progress')
      ) THEN
        CONTINUE;
      END IF;

      case_title := replace(replace(w.title_tpl, '{plot}', COALESCE(plot, a.nursery_name)),
                            '{nursery}', a.nursery_name);

      INSERT INTO nelos_cases (
        title, description, category, priority, status,
        source_module, source_ref, nursery_name, plot_name,
        assigned_module, assigned_seat_no, assignee_id, assignee_name,
        due_date, raised_by, automation_id
      ) VALUES (
        case_title,
        a.note,
        w.label,
        a.priority,
        'open',
        COALESCE(a.to_module, 'nelos'),
        -- Straight to the Auditor Portal module that records this, on this
        -- plot. audit_deeplink.js reads ?nursery= and ?plot=.
        CASE WHEN w.audit_href IS NULL THEN NULL
             ELSE w.audit_href || '?nursery=' || a.nursery_name ||
                  CASE WHEN plot IS NULL THEN '' ELSE '&plot=' || plot END
        END,
        a.nursery_name,
        plot,
        a.to_module,
        a.to_seat_no,
        a.assignee_id,
        a.assignee_name,
        CURRENT_DATE + a.due_days,
        'Automation',
        a.id
      );
      made := made + 1;
    END LOOP;

    UPDATE nelos_automations
       SET last_run_on = CURRENT_DATE,
           last_raised = made,
           next_run_on = public.nelos_next_run(CURRENT_DATE, a.repeat_every, a.on_day)
     WHERE id = a.id;

    automation_id := a.id;
    raised := made;
    RETURN NEXT;
  END LOOP;
END $$;

GRANT EXECUTE ON FUNCTION public.nelos_run_automations() TO authenticated;
GRANT EXECUTE ON FUNCTION public.nelos_next_run(DATE, TEXT, INT) TO authenticated;

-- ────────────────────────────────────────────────────────────────
-- PART 5: Who may change a schedule
--
-- The same rule the other settings tables use: everybody holding Nelos may
-- read, only an admin may change. A standing instruction that raises work
-- for other people is a setting, not casework.
-- ────────────────────────────────────────────────────────────────
DO $$
DECLARE t TEXT; pol RECORD;
BEGIN
  FOREACH t IN ARRAY ARRAY['nelos_automations', 'nelos_work_types'] LOOP
    FOR pol IN SELECT policyname FROM pg_policies
                WHERE schemaname = 'public' AND tablename = t
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, t);
    END LOOP;

    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format($p$
      CREATE POLICY "nelos read" ON public.%I
        FOR SELECT TO authenticated USING (public.nelos_has_access())$p$, t);
    EXECUTE format($p$
      CREATE POLICY "nelos admin write" ON public.%I
        FOR ALL TO authenticated
        USING (public.nelos_is_admin()) WITH CHECK (public.nelos_is_admin())$p$, t);
  END LOOP;
END $$;

-- ── Check it landed ─────────────────────────────────────────────
SELECT key, label, audit_href, title_tpl FROM nelos_work_types ORDER BY sort_order;

SELECT 'weekly, Monday'  AS rule, public.nelos_next_run(CURRENT_DATE, 'weekly', 1)  AS next_run
UNION ALL
SELECT 'monthly, 1st',        public.nelos_next_run(CURRENT_DATE, 'monthly', 1)
UNION ALL
SELECT 'monthly, 28th',       public.nelos_next_run(CURRENT_DATE, 'monthly', 28);

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   ALTER TABLE nelos_cases DROP COLUMN IF EXISTS automation_id;
--   DROP FUNCTION IF EXISTS public.nelos_run_automations();
--   DROP FUNCTION IF EXISTS public.nelos_next_run(DATE, TEXT, INT);
--   DROP TABLE IF EXISTS nelos_automations;
--   DROP TABLE IF EXISTS nelos_work_types;
