-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nursery_ops.sql
--
-- New module: NURSERY OPERATION MANAGEMENT (nops_*)
--   1. nops_work_types      — Motion Study: the work types a plot goes
--                             through (Soil Transport, Polybag Filling, …)
--                             with the standard days / crew each one needs.
--                             Fully editable — add & remove from the module's
--                             Settings page, nothing is hard-coded.
--   2. nops_seed_schedules  — Seeds Management: scheduled seeds-in.
--   3. nops_seed_receipts   — Seeds Management: actual receives against a
--                             schedule (partial deliveries supported).
--   4. nops_plot_works      — one row per piece of plot work. Powers BOTH
--                             the Monthly Schedule page (preset this / next
--                             month, history of what is done) AND the Life
--                             of Plot page (everything ever done on a plot).
--                             Plots come from the existing shared_plots —
--                             the same plots managed in the Nursery Seedling
--                             Stock Management settings.
--
-- Module access: permissions.modules.nursery_ops = 'admin'|'normal'|'none',
-- granted on the main portal's User Access (JSONB — no DDL needed).
--
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- ============================================================================

-- ────────────────────────────────────────────────────────────────
-- PART 1: Motion Study work types
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_work_types (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  sort_order  INT  NOT NULL DEFAULT 0,
  std_days    NUMERIC,      -- usual number of days this work takes for one plot
  std_crew    INT,          -- usual number of workers needed
  remark      TEXT,         -- motion-study notes (method, tools, pace…)
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nops_work_types ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_work_types'
       AND policyname='Authenticated read work types'
  ) THEN
    CREATE POLICY "Authenticated read work types" ON nops_work_types
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_work_types'
       AND policyname='Authenticated write work types'
  ) THEN
    CREATE POLICY "Authenticated write work types" ON nops_work_types
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Starter work types (the module Settings page can add/remove/edit these).
INSERT INTO nops_work_types (name, sort_order) VALUES
  ('Soil Transport',           1),
  ('Polybag Filling',          2),
  ('Polybag Lining',           3),
  ('Transplanting',            4),
  ('Seedling Maturing',        5),
  ('Seedling Open Collection', 6),
  ('3rd Culling',              7)
ON CONFLICT (name) DO NOTHING;

-- ────────────────────────────────────────────────────────────────
-- PART 2: Seeds Management — scheduled seeds-in
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_seed_schedules (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  breed           TEXT NOT NULL,
  supplier        TEXT,
  scheduled_date  DATE NOT NULL,
  scheduled_qty   INT  NOT NULL CHECK (scheduled_qty > 0),
  remark          TEXT,
  status          TEXT NOT NULL DEFAULT 'scheduled'
                  CHECK (status IN ('scheduled','partial','received','cancelled')),
  created_by      TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nops_seed_schedules_date_idx
  ON nops_seed_schedules (scheduled_date);

ALTER TABLE nops_seed_schedules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_seed_schedules'
       AND policyname='Authenticated read seed schedules'
  ) THEN
    CREATE POLICY "Authenticated read seed schedules" ON nops_seed_schedules
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_seed_schedules'
       AND policyname='Authenticated write seed schedules'
  ) THEN
    CREATE POLICY "Authenticated write seed schedules" ON nops_seed_schedules
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Seeds Management — actual receives (per schedule)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_seed_receipts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id    BIGINT NOT NULL REFERENCES nops_seed_schedules(id) ON DELETE CASCADE,
  received_date  DATE NOT NULL,
  qty            INT  NOT NULL CHECK (qty > 0),
  remark         TEXT,
  received_by    TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nops_seed_receipts_schedule_idx
  ON nops_seed_receipts (schedule_id);

ALTER TABLE nops_seed_receipts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_seed_receipts'
       AND policyname='Authenticated read seed receipts'
  ) THEN
    CREATE POLICY "Authenticated read seed receipts" ON nops_seed_receipts
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_seed_receipts'
       AND policyname='Authenticated write seed receipts'
  ) THEN
    CREATE POLICY "Authenticated write seed receipts" ON nops_seed_receipts
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Plot works — Monthly Schedule + Life of Plot
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nops_plot_works (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month          TEXT NOT NULL,     -- 'YYYY-MM' schedule bucket
  nursery_name   TEXT,
  plot_name      TEXT NOT NULL,     -- from shared_plots (same plots as the
                                    -- Seedling Stock Management settings)
  work_type_id   BIGINT REFERENCES nops_work_types(id) ON DELETE SET NULL,
  work_type      TEXT NOT NULL,     -- name snapshot — history survives even
                                    -- if the work type is later removed
  planned_start  DATE,
  planned_days   NUMERIC,           -- prefilled from the motion study std_days
  status         TEXT NOT NULL DEFAULT 'planned'
                 CHECK (status IN ('planned','in_progress','done','cancelled')),
  actual_start   DATE,
  actual_end     DATE,
  done_by        TEXT,
  remark         TEXT,
  created_by     TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nops_plot_works_month_idx ON nops_plot_works (month);
CREATE INDEX IF NOT EXISTS nops_plot_works_plot_idx  ON nops_plot_works (plot_name);

ALTER TABLE nops_plot_works ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_works'
       AND policyname='Authenticated read plot works'
  ) THEN
    CREATE POLICY "Authenticated read plot works" ON nops_plot_works
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nops_plot_works'
       AND policyname='Authenticated write plot works'
  ) THEN
    CREATE POLICY "Authenticated write plot works" ON nops_plot_works
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;
