-- =====================================================================
-- RUN_ME_maintenance_audit_save.sql
-- Make the Maintenance Audit save — and keep saving.
--
-- Paste the whole file into the Supabase SQL Editor and run it once.
-- Safe to run again. A second run changes nothing and prints the same
-- answers.
--
-- It fixes the three database-side reasons an audit of plot U18 cannot
-- land, and ends by telling you which of them were actually wrong.
--
--   1. A FOREIGN KEY on task_id. Audit tasks come from two places (see
--      audit/audit_maintenance_script.js loadAll): real rows in
--      nops_maint_field_records with real ids, and rows inside the JSONB
--      blob of nops_maint_records whose ids are JS timestamps existing in
--      no table at all. A foreign key rejects every audit of the second
--      kind - Postgres 23503 - which the phone reports as "A linked
--      record (batch or task) is missing". No migration in this
--      repository ever created that constraint. It was added by hand.
--   2. A missing column. The app writes audit_id, task_id, nursery, plot,
--      task_type, result, remarks, photo_url, date and auditor_name.
--   3. A missing or private audit-photos bucket. A photo is compulsory on
--      this form, so storage refusing the write fails the save with it.
-- =====================================================================


-- ── 1. No foreign keys on the audit table ────────────────────────────
DO $$
DECLARE c RECORD;
BEGIN
  IF to_regclass('public.audit_maintenance_audits') IS NULL THEN
    RAISE NOTICE 'audit_maintenance_audits is not in this database - nothing to do';
    RETURN;
  END IF;
  FOR c IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'public.audit_maintenance_audits'::regclass AND contype = 'f'
  LOOP
    EXECUTE 'ALTER TABLE public.audit_maintenance_audits DROP CONSTRAINT ' || quote_ident(c.conname);
    RAISE NOTICE 'dropped foreign key: %', c.conname;
  END LOOP;
END $$;


-- ── 2. Every column the app writes ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_maintenance_audits (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.audit_maintenance_audits
  ADD COLUMN IF NOT EXISTS created_at   TIMESTAMPTZ DEFAULT now(),
  ADD COLUMN IF NOT EXISTS audit_id     TEXT,
  ADD COLUMN IF NOT EXISTS task_id      BIGINT,
  ADD COLUMN IF NOT EXISTS nursery      TEXT,
  ADD COLUMN IF NOT EXISTS plot         TEXT,
  ADD COLUMN IF NOT EXISTS task_type    TEXT,
  ADD COLUMN IF NOT EXISTS result       TEXT,
  ADD COLUMN IF NOT EXISTS remarks      TEXT,
  ADD COLUMN IF NOT EXISTS photo_url    TEXT,
  ADD COLUMN IF NOT EXISTS date         DATE,
  ADD COLUMN IF NOT EXISTS auditor_name TEXT;


-- ── 3. The audit-photos bucket, public to read ───────────────────────
--
-- Public because the phone shows the photo back from a plain URL. The
-- write still needs a signed-in role. See the policies below.
DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NULL THEN
    RAISE NOTICE 'no storage schema here - skipping the bucket';
    RETURN;
  END IF;
  INSERT INTO storage.buckets (id, name, public)
  VALUES ('audit-photos', 'audit-photos', true)
  ON CONFLICT (id) DO UPDATE SET public = true;
END $$;

-- The policies that let an auditor write one and anybody read it.
-- Wrapped: on some projects storage.objects is not owned by the role
-- running the SQL Editor, and a refusal here must not stop the rest of
-- the file - the bucket above is the part that usually matters.
DO $$
BEGIN
  IF to_regclass('storage.objects') IS NULL THEN RETURN; END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname='storage' AND tablename='objects'
                    AND policyname='audit photos readable') THEN
    CREATE POLICY "audit photos readable" ON storage.objects
      FOR SELECT USING (bucket_id = 'audit-photos');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname='storage' AND tablename='objects'
                    AND policyname='audit photos writable') THEN
    CREATE POLICY "audit photos writable" ON storage.objects
      FOR INSERT TO authenticated WITH CHECK (bucket_id = 'audit-photos');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                  WHERE schemaname='storage' AND tablename='objects'
                    AND policyname='audit photos replaceable') THEN
    CREATE POLICY "audit photos replaceable" ON storage.objects
      FOR UPDATE TO authenticated USING (bucket_id = 'audit-photos');
  END IF;
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'could not set storage policies from here - set them in Storage > Policies';
END $$;

NOTIFY pgrst, 'reload schema';


-- ── The check ────────────────────────────────────────────────────────
-- A good result is four rows, every one of them starting OK.
SELECT 1 AS n, 'foreign keys on the audit table: ' || count(*)::text ||
       CASE WHEN count(*) = 0 THEN ' -- OK'
            ELSE ' -- NOT OK: ' || string_agg(conname, ', ') END AS result
  FROM pg_constraint
 WHERE conrelid = to_regclass('public.audit_maintenance_audits') AND contype = 'f'
UNION ALL
SELECT 2, 'columns the app writes, present: ' || count(*)::text || ' of 10' ||
       CASE WHEN count(*) = 10 THEN ' -- OK'
            ELSE ' -- NOT OK, missing: ' || (
              SELECT string_agg(c, ', ') FROM unnest(ARRAY['audit_id','task_id','nursery','plot',
                     'task_type','result','remarks','photo_url','date','auditor_name']) AS c
               WHERE c NOT IN (SELECT column_name FROM information_schema.columns
                                WHERE table_schema='public' AND table_name='audit_maintenance_audits')) END
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'audit_maintenance_audits'
   AND column_name IN ('audit_id','task_id','nursery','plot','task_type',
                       'result','remarks','photo_url','date','auditor_name')
UNION ALL
SELECT 3, CASE
       WHEN to_regclass('storage.buckets') IS NULL THEN 'audit-photos bucket: no storage schema -- CHECK BY HAND'
       WHEN EXISTS (SELECT 1 FROM storage.buckets WHERE id='audit-photos' AND public)
            THEN 'audit-photos bucket: present and public -- OK'
       WHEN EXISTS (SELECT 1 FROM storage.buckets WHERE id='audit-photos')
            THEN 'audit-photos bucket: present but PRIVATE -- NOT OK'
       ELSE 'audit-photos bucket: MISSING -- NOT OK' END
UNION ALL
SELECT 4, CASE
       WHEN to_regclass('storage.objects') IS NULL THEN 'storage policies: no storage schema -- CHECK BY HAND'
       WHEN (SELECT count(*) FROM pg_policies WHERE schemaname='storage' AND tablename='objects'
              AND policyname LIKE 'audit photos%') >= 3
            THEN 'storage policies for audit-photos: 3 of 3 -- OK'
       ELSE 'storage policies for audit-photos: ' ||
            (SELECT count(*)::text FROM pg_policies WHERE schemaname='storage' AND tablename='objects'
              AND policyname LIKE 'audit photos%') ||
            ' of 3 -- set the rest in Storage > Policies' END
ORDER BY n;
